FROM maven:latest

# point to container working directory
WORKDIR /server

# copy all Spring Boot files
COPY . /server

# expose port and start server
EXPOSE ${SERVER_PORT}
ENTRYPOINT ["mvn","spring-boot:run"]